/*
 * Copyright (c) 2023.
 * @author Patrick Mutwiri on 5/24/23, 10:35 PM
 */

INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,101,'CHANGAMWE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,102,'JOMVU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,103,'KISAUNI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,104,'LIKONI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,105,'MVITA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (1,106,'NYALI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (2,201,'KINANGO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (2,202,'LUNGA LUNGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (2,203,'MATUGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (2,204,'MSAMBWENI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (2,205,'SAMBURU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,301,'CHONYI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,302,'GANZE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,303,'KALOLENI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,304,'KAUMA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,305,'KILIFI NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,306,'KILIFI SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,307,'MAGARINI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,308,'MALINDI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (3,309,'RABAI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (4,401,'TANA DELTA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (4,402,'TANA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (4,403,'TANA RIVER');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (5,501,'LAMU EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (5,502,'LAMU WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (6,601,'MWATATE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (6,602,'TAITA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (6,603,'TAVETA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (6,604,'VOI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,701,'BALAMBALA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,702,'DADAAB');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,703,'FAFI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,704,'GARISSA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,705,'HULUGHO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,706,'IJARA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (7,707,'LAGDERA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,801,'BUNA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,802,'ELDAS');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,803,'HABASWEIN');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,804,'TARBAJ');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,805,'WAJIR EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,806,'WAJIR NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,807,'WAJIR SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (8,808,'WAJIR WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,901,'MANDERA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,902,'BANISA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,903,'KOTULO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,904,'LAFEY');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,905,'MANDERA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,906,'MANDERA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (9,907,'MANDERA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1001,'LOIYANGALANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1002,'MARSABIT CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1003,'MARSABIT NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1004,'MARSABIT SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1005,'MOYALE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1006,'NORTH HORR');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (10,1007,'SOLOLO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (11,1101,'GARBATULLA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (11,1102,'ISIOLO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (11,1103,'MERTI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1201,'BUURI EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1202,'BUURI WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1203,'IGEMBE CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1204,'IGEMBE NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1205,'IGEMBE SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1206,'IMENTI NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1207,'IMENTI SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1208,'MERU CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1209,'TIGANIA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1210,'TIGANIA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (12,1211,'TIGANIA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (13,1301,'IGAMBANG''OMBE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (13,1302,'MAARA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (13,1303,'MERU SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (13,1304,'THARAKA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (13,1305,'THARAKA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (14,1401,'EMBU EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (14,1402,'EMBU NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (14,1403,'EMBU WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (14,1404,'MBEERE SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (14,1405,'MBEERE NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1501,'IKUTHA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1502,'KATULANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1503,'KISASI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1504,'KITUI CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1505,'KITUI WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1506,'KYUSO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1507,'LOWER YATTA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1508,'MATINYANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1509,'MIGWANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1510,'MUMONI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1511,'MUTITU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1512,'MUTITU NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1513,'MUTOMO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1514,'MWINGI CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1515,'MWINGI EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1516,'NZAMBANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1517,'THAGICU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (15,1518,'TSEIKURU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1601,'ATHI RIVER');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1602,'KALAMA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1603,'KANGUNDO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1604,'KATHIANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1605,'MACHAKOS');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1606,'MASINGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1607,'MATUNGULU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1608,'MWALA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (16,1609,'YATTA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1701,'KATHONZWENI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1702,'KIBWEZI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1703,'KILUNGU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1704,'MAKINDU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1705,'MAKUENI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1706,'MBOONI EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1707,'MBOONI WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1708,'MUKAA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (17,1709,'NZAUI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1801,'KINANGOP');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1802,'NYANDARUA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1803,'MIRANGINE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1804,'KIPIPIRI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1805,'NYANDARUA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1806,'NYANDARUA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1807,'NYANDARUA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (18,1901,'TETU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1902,'KIENI EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1903,'KIENI WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1904,'MATHIRA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1905,'MATHIRA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1906,'NYERI SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1907,'MUKURWE-INI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,1908,'NYERI CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (19,2001,'KIRINYAGA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (20,2002,'KIRINYAGA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (20,2003,'KIRINYAGA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (20,2004,'MWEA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (20,2005,'MWEA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (20,2101,'MURANG''A EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2102,'KANGEMA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2103,'MATHIOYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2104,'KAHURO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2105,'MURANG''A SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2106,'GATANGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2107,'KIGUMO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2108,'KANDARA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (21,2201,'GATUNDU NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2202,'GATUNDU SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2203,'GITHUNGURI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2204,'JUJA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2205,'KABETE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2206,'KIAMBAA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2207,'KIAMBU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2208,'KIKUYU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2209,'LARI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2210,'LIMURU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2211,'RUIRU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2212,'THIKA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2213,'THIKA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (22,2301,'KIBISH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2302,'LOIMA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2303,'TURKANA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2304,'TURKANA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2305,'TURKANA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2306,'TURKANA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2307,'TURKANA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (23,2401,'KIPKOMO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (24,2402,'POKOT CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (24,2403,'POKOT NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (24,2404,'POKOT SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (24,2405,'WEST POKOT');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (24,2501,'SAMBURU CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (25,2502,'SAMBURU EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (25,2503,'SAMBURU NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (25,2601,'TRANS NZOIA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (26,2602,'TRANS NZOIA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (26,2603,'KWANZA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (26,2604,'ENDEBESS');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (26,2605,'KIMININI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (26,2701,'AINABKOI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (27,2702,'KAPSERET');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (27,2703,'KESSES');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (27,2704,'MOIBEN');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (27,2705,'SOY');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (27,2706,'TURBO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (28,2801,'KEIYO NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (28,2802,'KEIYO SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (28,2803,'MARAKWET EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (28,2804,'MARAKWET WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2901,'CHESUMEI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2902,'NANDI CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2903,'NANDI EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2904,'NANDI NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2905,'NANDI SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (29,2906,'TINDERET');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3001,'BARINGO CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3002,'BARINGO NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3003,'EAST POKOT');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3004,'KOIBATEK');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3005,'MARIGAT');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3006,'MOGOTIO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3007,'TIATY EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (30,3008,'LAKE BARINGO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (31,3101,'LAIKIPIA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (31,3102,'LAIKIPIA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (31,3103,'LAIKIPIA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (31,3104,'LAIKIPIA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (31,3105,'NYAHURURU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3201,'GILGIL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3202,'KURESOI NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3203,'KURESOI SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3204,'MOLO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3205,'NAIVASHA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3206,'NAKURU EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3207,'NAKURU NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3208,'NAKURU WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3209,'NJORO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3210,'RONGAI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (32,3211,'SUBUKIA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3301,'NAROK EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3302,'NAROK NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3303,'NAROK SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3304,'NAROK WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3305,'TRANS MARA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (33,3306,'TRANS MARA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3401,'ISINYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3402,'KAJIADO CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3403,'KAJIADO NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3404,'KAJIADO WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3405,'LOITOKITOK');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (34,3406,'MASHUURU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3501,'BELGUT');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3502,'BURETI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3503,'KERICHO EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3504,'KIPKELION');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3505,'LONDIANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (35,3506,'SOIN SIGOWET');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (36,3601,'BOMET EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (36,3602,'CHEPALUNGU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (36,3603,'KONOIN');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (36,3604,'SOTIK');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (36,3605,'BOMET CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3701,'BUTERE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3702,'KAKAMEGA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3703,'KAKAMEGA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3704,'KAKAMEGA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3705,'KAKAMEGA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3706,'KHWISERO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3707,'LIKUYANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3708,'LUGARI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3709,'MATETE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3710,'MATUNGU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3711,'MUMIAS EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3712,'MUMIAS WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (37,3713,'NAVAKHOLO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (38,3801,'EMUHAYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (38,3802,'VIHIGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (38,3803,'SABATIA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (38,3804,'LUANDA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (38,3805,'HAMISI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3901,'BUMULA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3902,'BUNGOMA CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3903,'BUNGOMA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3904,'BUNGOMA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3905,'BUNGOMA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3906,'CHEPTAIS');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3907,'KIMILILI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3909,'BUNGOMA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3910,'TONGAREN');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3911,'WEBUYE WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (39,3912,'MT ELGON FOREST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4001,'BUNYALA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4002,'BUSIA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4003,'BUTULA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4004,'NAMBALE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4005,'SAMIA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4006,'TESO NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (40,4007,'TESO SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4101,'SIAYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4102,'GEM');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4103,'UGENYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4104,'UGUNJA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4105,'BONDO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (41,4106,'RARIEDA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4201,'KISUMU EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4202,'KISUMU CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4203,'KISUMU WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4204,'SEME');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4205,'MUHORONI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4206,'NYANDO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (42,4207,'NYAKACH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4301,'HOMA BAY');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4302,'NDHIWA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4303,'RACHUONYO NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4304,'RACHUONYO EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4305,'RACHUONYO SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4306,'RANGWE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4307,'SUBA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (43,4308,'SUBA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4401,'AWENDO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4402,'KURIA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4403,'KURIA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4404,'NYATIKE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4405,'RONGO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4406,'SUNA EAST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4407,'SUNA WEST');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (44,4408,'URIRI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4501,'ETAGO');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4502,'GUCHA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4503,'GUCHA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4504,'KENYENYA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4505,'KISII CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4506,'KISII SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4507,'KITUTU CENTRAL');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4508,'MARANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4509,'MASABA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4510,'NYAMACHE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (45,4511,'SAMETA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (46,4601,'BORABU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (46,4602,'MANGA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (46,4603,'MASABA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (46,4604,'NYAMIRA NORTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (46,4605,'NYAMIRA SOUTH');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4701,'DAGORETTI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4702,'EMBAKASI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4703,'KAMUKUNJI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4704,'KASARANI');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4705,'KIBRA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4706,'LANG''ATA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4707,'MAKADARA');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4708,'MATHARE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4709,'NJIRU');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4710,'STAREHE');
INSERT INTO sub_counties(county_id,sub_county_id,name) VALUES (47,4711,'WESTLANDS');
